version: '3'
services:
  jupyter:
    build:
      context: ./
      dockerfile: ./cm203-gpu/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - "./notebooks/:/project"
      - "./content/:/content"
    shm_size: '2gb'
    image: gabrui/cm203-gpu:v0.1.lab03
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
